### ISSUE TITLE
使用文档中应该把依赖放在dependencies中

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/ant-motion#13]
![image](https://cloud.githubusercontent.com/assets/4705237/18429962/ee68829e-7908-11e6-8c1b-0a943b9411d8.png)
动效的组件应该放在dependencies中吧,devDependencies是用在开发阶段的

**Comment by velenooo** [comment]
虽然过了好久了。依然谢谢。-------- 原始邮件 --------主题：[ant-design/ant-motion] 使用文档中应该把依赖放在dependencies中 (#13)发件人：兼续 收件人：ant-design/ant-motion 抄送：
动效的组件应该放在dependencies中吧,devDependencies是用在开发阶段的

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-motion","title":"ant-design/ant-motion","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-motion"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"使用文档中应该把依赖放在dependencies中 (#13)"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-motion/issues/13"}}}

**Comment by jljsj33** [comment]
这楼上什么鬼。。。。

收到，，我改下，，其实问题不大。。。哈哈。。

**Comment by velenooo** [comment]
我也想问。为什么我也收到邮件？原来不是我的？-------- 原始邮件 --------主题：Re: [ant-design/ant-motion] 使用文档中应该把依赖放在dependencies中 (#13)发件人：jiang 收件人：ant-design/ant-motion 抄送：velenooo ,Comment 这楼上什么鬼。。。。

收到，，我改下，，其实问题不大。。。哈哈。。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-motion","title":"ant-design/ant-motion","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-motion"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jljsj33 in #13: 这楼上什么鬼。。。。\r\n\r\n收到，，我改下，，其实问题不大。。。哈哈。。"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-motion/issues/13#issuecomment-246322083"}}}

**Comment by jljsj33** [comment]
活人的啊，，我还以为是机器人。。。。

@velenooo 你可能关注了

**Comment by jljsj33** [comment]
unwatch

**Comment by rdmclin2** [comment]
@jljsj33 噗，看到你github profile的地点写的hangzou:smile:

**Comment by jljsj33** [comment]
hangzou 错了吗？

**Comment by jljsj33** [comment]
额。。。打五笔的，，别问我基本拼音。。。不会。。。。

**Comment by rdmclin2** [comment]
哈哈，应该是hangzhou，小鹤双拼路过hhvz
